/*
 * Trabalho 1 - Arquitetura de Computadores 2 
 * 
 * Simulador do ARM7
 * 
 * Alunos: Carlos Daniel Drury
 *	   Frederico
 *         Gabriel Almeida Miranda
 *         Leonardo Almeida de Araújo
 *         Juliano
 *
 * Implementação na linguagem JAVA
 * IDE utilizada para execução e compilação: NetBeans 7.3
 * Plataformas testadas: Windows 7 e Ubuntu 12.10
 *
 */


package trabarq2;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

public class Window extends javax.swing.JFrame {

    /** Creates new form Window */
    public Window() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bancoRegistradores = new javax.swing.JTable();
        labelInstrucao = new javax.swing.JLabel();
        textInstrucao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pc = new javax.swing.JTextArea();
        instrucaoAtualBin = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        instrucoes = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        proximo = new javax.swing.JButton();
        labelStatusMemoria = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        memoryStatus = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textIDecoder = new javax.swing.JTextField();
        textIExec = new javax.swing.JTextField();
        Pipeline = new javax.swing.JPanel();
        labelExecute = new javax.swing.JLabel();
        labelDecode = new javax.swing.JLabel();
        labelFetch = new javax.swing.JLabel();
        estagios = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        fecharMenu = new javax.swing.JMenuItem();
        sairMenu = new javax.swing.JMenuItem();
        execMenuMenu = new javax.swing.JMenu();
        execAllMenu = new javax.swing.JMenuItem();
        executarMenu = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador ARM7");
        setResizable(false);

        jLabel12.setText("Registradores:");

        bancoRegistradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"$R0", null},
                {"$R1", null},
                {"$R2", null},
                {"$R3", null},
                {"$R4", null},
                {"$R5", null},
                {"$R6", null},
                {"$R7", null},
                {"$R8", null},
                {"$R9", null},
                {"$R10", null},
                {"$R11", null},
                {"$R12", null},
                {"$R13", null},
                {"$R14", null},
                {"$R15 (PC)", null},
                {"CPSR ", null},
                {"CPSR, SPSR_fiq ", null},
                {"CPSR, SPSR_irq ", null},
                {"CPSR, SPSR_svc ", null},
                {"CPSR, SPSR_abt ", null},
                {"CPSR, SPSR_und ", null},
                {"$22", null},
                {"$23", null},
                {"$24", null},
                {"$25", null},
                {"$26", null},
                {"$27", null},
                {"$28", null},
                {"$29", null},
                {"$30", null},
                {"$31", null}
            },
            new String [] {
                "Registrador", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bancoRegistradores.getTableHeader().setReorderingAllowed(false);
        bancoRegistradoresModel = bancoRegistradores.getModel();
        bancoRegistradores.setAutoResizeMode(0);
        bancoRegistradores.getColumnModel().getColumn(0).setPreferredWidth(100);
        bancoRegistradores.getColumnModel().getColumn(1).setPreferredWidth(304);
        jScrollPane4.setViewportView(bancoRegistradores);
        bancoRegistradores.getColumnModel().getColumn(0).setResizable(false);
        bancoRegistradores.getColumnModel().getColumn(1).setResizable(false);

        labelInstrucao.setText("Busca de Instrução:");

        textInstrucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInstrucaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Instruções a serem executadas:");

        pc.setEditable(false);
        pc.setColumns(20);
        pc.setRows(5);
        pc.setAutoscrolls(false);
        pc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pc.setMinimumSize(new java.awt.Dimension(0, 0));

        instrucaoAtualBin.setEditable(false);
        instrucaoAtualBin.setColumns(20);
        instrucaoAtualBin.setRows(5);
        instrucaoAtualBin.setAutoscrolls(false);
        instrucaoAtualBin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        instrucaoAtualBin.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel3.setText("Instrução atual (formato binário):");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setHorizontalScrollBar(null);

        instrucoes.setEditable(false);
        instrucoes.setColumns(20);
        instrucoes.setRows(5);
        jScrollPane2.setViewportView(instrucoes);

        jLabel9.setText("PC:");

        proximo.setText("Próxima");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        labelStatusMemoria.setText("Status da Memória:");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setHorizontalScrollBar(null);

        memoryStatus.setEditable(false);
        memoryStatus.setColumns(20);
        memoryStatus.setRows(5);
        jScrollPane3.setViewportView(memoryStatus);

        jLabel2.setText("Instrução Decodificada:");

        jLabel4.setText("Execução:");

        Pipeline.setLayout(null);
        Pipeline.add(labelExecute);
        labelExecute.setBounds(300, 20, 150, 20);
        Pipeline.add(labelDecode);
        labelDecode.setBounds(150, 20, 130, 20);
        Pipeline.add(labelFetch);
        labelFetch.setBounds(20, 20, 130, 20);

        estagios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabarq2/pipeline.jpg"))); // NOI18N
        Pipeline.add(estagios);
        estagios.setBounds(10, 0, 510, 160);

        jMenu1.setText("Arquivo");

        menuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuItemAbrir.setText("Abrir");
        menuItemAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                menuItemAbrirMouseReleased(evt);
            }
        });
        jMenu1.add(menuItemAbrir);

        fecharMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        fecharMenu.setText("Fechar");
        fecharMenu.setEnabled(false);
        fecharMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fecharMenuMouseReleased(evt);
            }
        });
        jMenu1.add(fecharMenu);

        sairMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        sairMenu.setText("Sair");
        sairMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sairMenuMouseReleased(evt);
            }
        });
        jMenu1.add(sairMenu);

        mainMenu.add(jMenu1);

        execMenuMenu.setText("Execução");
        execMenuMenu.setEnabled(false);

        execAllMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        execAllMenu.setText("Executar tudo");
        execAllMenu.setEnabled(false);
        execMenuMenu.add(execAllMenu);

        executarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        executarMenu.setText("Executar por instrução");
        executarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                executarMenuMouseReleased(evt);
            }
        });
        execMenuMenu.add(executarMenu);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem7.setText("Executar por estágio");
        jMenuItem7.setEnabled(false);
        execMenuMenu.add(jMenuItem7);

        mainMenu.add(execMenuMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proximo))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelInstrucao)
                            .addComponent(textInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(instrucaoAtualBin, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(textIExec, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(textIDecoder)
                            .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelStatusMemoria)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                            .addComponent(Pipeline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(proximo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textInstrucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(instrucaoAtualBin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textIDecoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textIExec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelStatusMemoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pipeline, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void textInstrucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInstrucaoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_textInstrucaoActionPerformed

private void menuItemAbrirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemAbrirMouseReleased
        fileOpenDialog = new javax.swing.JFileChooser();
        fileOpenDialog.setCurrentDirectory(new java.io.File("C:\\"));
        fileOpenDialog.setDialogTitle("Abrir Arquivo ASM");
        
        int returnValue = fileOpenDialog.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            Interpretador.clearAll();
            Interpretador.setArquivo(fileOpenDialog.getSelectedFile());

            instrucoes.setText(Interpretador.getFileContents());

            fecharMenu.setEnabled(true);
            execMenuMenu.setEnabled(true);
        }
}//GEN-LAST:event_menuItemAbrirMouseReleased

    public static void instrucaoAtual(String Instruction){
        textInstrucao.setText(Instruction);
    }

   
    
      public static void setPc(int num) {
        pc.setText(String.valueOf(num));
    }

    public static void setPc(String snum) {
        pc.setText(snum);
    }
    
    public static void setRegister(String data, int row) {
        bancoRegistradoresModel.setValueAt(data, row, 1);
    }

    public static void setInstrucaoAtualBin(String instBin) {
        instrucaoAtualBin.setText(instBin);
    }
    
     public static void setMemoryStatus(String mem) {
        memoryStatus.setText(memoryStatus.getText() + mem + "\n");
    }
    
    public static void setIDecoder(String instrucao){
        textIDecoder.setText(instrucao);
    }   
    
    public static void setIExec(String instrucao){
        textIExec.setText(instrucao);
    }
    
    public static void setLabelFetch(String instrucao){
        labelFetch.setText(instrucao);
    }
    
    public static void setLabelDecode(String instrucao){
        labelDecode.setText(instrucao);
    }
    
    public static void setLabelExecute(String instrucao){
        labelExecute.setText(instrucao);
    }
    
     
     public static void setSinalDeControle(String sinal, int row) {
        sinaisDeControleModel.setValueAt(sinal, row, 1);
    }
     
  public static void clean(){
      int i;
      for (i=0; i< 32; i++){
          setRegister("",i);
      }
      setInstrucaoAtualBin("");
      setMemoryStatus("");
      setIDecoder("");
      setIExec("");
  }
    
  public static void stop(){
      proximo.setVisible(false);
  }

private void fecharMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharMenuMouseReleased
        Interpretador.clearAll();


        instrucoes.setText(null);
        pc.setText(null);
        //instrucaoAtual.setText(null);
        instrucaoAtualBin.setText(null);
       
        fecharMenu.setEnabled(false);
        execMenuMenu.setEnabled(false);
}//GEN-LAST:event_fecharMenuMouseReleased




private void sairMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMenuMouseReleased
        System.exit(0);
}//GEN-LAST:event_sairMenuMouseReleased

private void executarMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_executarMenuMouseReleased
        try {
            Interpretador.RunInstruction();
        } catch (Exception ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_executarMenuMouseReleased

private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        try {
            // TODO add your handling code here:
                Interpretador.RunInstruction();
        } catch (Exception ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}//GEN-LAST:event_proximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Window().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pipeline;
    private static javax.swing.JTable bancoRegistradores;
    private javax.swing.JLabel estagios;
    private javax.swing.JMenuItem execAllMenu;
    private javax.swing.JMenu execMenuMenu;
    private javax.swing.JMenuItem executarMenu;
    private javax.swing.JMenuItem fecharMenu;
    private static javax.swing.JTextArea instrucaoAtualBin;
    private static javax.swing.JTextArea instrucoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private static javax.swing.JLabel labelDecode;
    private static javax.swing.JLabel labelExecute;
    private static javax.swing.JLabel labelFetch;
    private javax.swing.JLabel labelInstrucao;
    private javax.swing.JLabel labelStatusMemoria;
    private javax.swing.JMenuBar mainMenu;
    private static javax.swing.JTextArea memoryStatus;
    private javax.swing.JMenuItem menuItemAbrir;
    private static javax.swing.JTextArea pc;
    private static javax.swing.JButton proximo;
    private javax.swing.JMenuItem sairMenu;
    private static javax.swing.JTextField textIDecoder;
    private static javax.swing.JTextField textIExec;
    private static javax.swing.JTextField textInstrucao;
    // End of variables declaration//GEN-END:variables
    private static javax.swing.JFileChooser fileOpenDialog;
    private static javax.swing.table.TableModel sinaisDeControleModel;
    private static javax.swing.table.TableModel bancoRegistradoresModel;
    private static javax.swing.table.TableModel sinaisEXEModel;
    private static javax.swing.table.TableModel dadosMEMModel;
    private static javax.swing.table.TableModel dadosWRModel;

    

}
